INSERT INTO task_collaborator (task_id, collaborator_id) VALUES
                                                             (1, 1),
                                                             (2, 1),
                                                             (2, 5),
                                                             (3, 3),
                                                             (4, 2),
                                                             (4, 4),
                                                             (5, 1),
                                                             (5, 5),
                                                             (6, 1),
                                                             (6, 5),
                                                             (7, 1),
                                                             (8, 2),
                                                             (8, 5),
                                                             (9, 2),
                                                             (10, 3);
